#!/bin/bash

echo "A Simple Wine Installer :)"

echo "Note This Was Made In 64bit xUbuntu 18.04"

sudo dpkg --add-architecture i386 
 wget -nc https://dl.winehq.org/wine-builds/winehq.key
  sudo apt-key add winehq.key
    sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
sudo apt update
sudo apt install --install-recommends winehq-stable

sudo bash wine-dependency

echo "Enjoy! Script By ZePh!"

echo "Wine is Now Installed!"